#!/usr/bin/env python3
"""
Build research/coa_fidelity/BLOCKED.md -- a single, human-readable retry
queue for every jurisdiction the COA-fidelity sweep marked `blocked` in
STATUS.yaml.

Why this exists: STATUS.yaml is a flat 195-row list. A `blocked` row (e.g.
Algeria, Morocco -- both blocked on this environment's outbound-HTTPS
allowlist, not on source non-existence) is easy to lose track of buried
among 194 other rows. This script pulls every `blocked` row out into one
place with its full notes, so a future session (or the sweep-close review)
can walk the list top to bottom and retry each one deliberately, instead of
re-discovering blocked jurisdictions by re-reading the whole tracker.

This script is read-only with respect to STATUS.yaml -- it never changes
fidelity_status. Retrying a blocked jurisdiction and updating its status is
still a normal sweep round (research/coa_fidelity/README.md), done in its
own worktree/branch/PR like any other round.

Usage:
    python3 scripts/coa_fidelity/build_blocked_report.py \
        --status research/coa_fidelity/STATUS.yaml \
        --out research/coa_fidelity/BLOCKED.md
"""
import argparse
import os
import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def build(status_path, out_path):
    doc = yaml.safe_load(open(status_path, encoding="utf-8"))
    rows = [j for j in doc["jurisdictions"] if j["fidelity_status"] == "blocked"]
    rows.sort(key=lambda r: (r["region"], r["name"]))

    total = doc["metadata"]["total_jurisdictions"]
    counts = doc["metadata"]["counts"]

    lines = []
    lines.append("# COA-fidelity sweep — blocked jurisdictions retry queue")
    lines.append("")
    lines.append(
        "**Auto-generated by `scripts/coa_fidelity/build_blocked_report.py` "
        "from `research/coa_fidelity/STATUS.yaml`. Do not hand-edit — rerun "
        "the script instead, it is idempotent and read-only w.r.t. STATUS.yaml.**"
    )
    lines.append("")
    lines.append(
        "`blocked` means: a round was attempted and a real obstacle was hit "
        "(most commonly: this session's outbound-HTTPS egress could not "
        "reach the primary source), **not** that no official source exists. "
        "Never treat a row here as permanently unresolvable -- retry it, "
        "ideally from a session/environment with working general-internet "
        "egress, before concluding the sweep can't cover it."
    )
    lines.append("")
    lines.append(
        f"**{len(rows)} of {total} jurisdictions blocked** "
        f"(verified: {counts.get('verified', 0)}, "
        f"partial_curated_subset: {counts.get('partial_curated_subset', 0)}, "
        f"n/a_no_statutory_chart: {counts.get('n/a_no_statutory_chart', 0)})."
    )
    lines.append("")

    if not rows:
        lines.append("_No blocked jurisdictions right now._")
    else:
        lines.append("## Summary table")
        lines.append("")
        lines.append("| ISO | Name | Region | Chart family | Last checked |")
        lines.append("|---|---|---|---|---|")
        for r in rows:
            lines.append(
                f"| `{r['iso']}` | {r['name']} | {r['region']} | "
                f"{r.get('chart_family') or '—'} | {r.get('last_checked') or '—'} |"
            )
        lines.append("")
        lines.append("## Per-jurisdiction detail")
        lines.append("")
        for r in rows:
            lines.append(f"### {r['name']} (`{r['iso']}`)")
            lines.append("")
            lines.append(f"- **Region:** {r['region']}")
            lines.append(f"- **Chart family:** {r.get('chart_family') or 'n/a'}")
            lines.append(f"- **Current localization codes (curated, unreplaced):** {r.get('current_localization_codes') if r.get('current_localization_codes') is not None else 'unknown'}")
            lines.append(f"- **Last checked:** {r.get('last_checked') or 'unknown'}")
            lines.append("- **Notes (verbatim from STATUS.yaml):**")
            lines.append("")
            note = (r.get("notes") or "").strip()
            lines.append(f"  > {note}" if note else "  > _(no notes recorded)_")
            lines.append("")

        lines.append("## Retry checklist (run per jurisdiction, at sweep-close or on demand)")
        lines.append("")
        lines.append(
            "1. Confirm current egress actually reaches an external government/"
            "regulator host (e.g. `curl -sS -o /dev/null -w '%{http_code}' "
            "<candidate-url>` from the notes above) before assuming the prior "
            "block still applies -- environments differ session to session."
        )
        lines.append(
            "2. If reachable: run a normal sweep round for that jurisdiction "
            "per `research/coa_fidelity/README.md` (own worktree/branch, "
            "`fix(<cc>): verified <N>-code official chart`, PR against "
            "`claude/coa-fidelity-sweep`)."
        )
        lines.append(
            "3. If still unreachable: leave `fidelity_status: blocked`, but "
            "update `last_checked` and append a dated note recording the "
            "retry attempt, so repeated retries don't look identical to the "
            "first one."
        )
        lines.append(
            "4. Rerun this script (`build_blocked_report.py`) after any "
            "STATUS.yaml change so this file stays in sync."
        )
        lines.append("")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {len(rows)} blocked jurisdiction(s) to {out_path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--status", default="research/coa_fidelity/STATUS.yaml")
    ap.add_argument("--out", default="research/coa_fidelity/BLOCKED.md")
    args = ap.parse_args()
    build(args.status, args.out)


if __name__ == "__main__":
    main()
